/**
 * Nova Crew Server - Auto-generated Configuration
 * This file is automatically generated when the server starts.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 */

// API Base URL - automatically configured from server port
window.NOVA_API_URL = 'http://localhost:9090';
